### ISSUE TITLE
Requesting Help for Smoke Testing

### ISSUE THREAD

**Issue by jayjay19630** [nus-cs2103-AY2425S1/forum#340]
Hi everyone, I'm a Mac user would really appreciate it if my jar file could be smoke tested. I'm open to any criticisms or suggestions!

Here are some resources you might need to test it:
- [Jar File](https://github.com/jayjay19630/ip/releases/tag/A-Release2)
- [User Guide](https://jayjay19630.github.io/ip/)

Thanks in advance!

**Comment by AbdulrahmanAlRammah** [comment]
Unable to run on Windows
![image](https://github.com/user-attachments/assets/69045ce7-b27d-43c8-8a7c-37180cd0d22a)

**Comment by jayjay19630** [comment]
Oops, looks like my build script didn't have the dependencies for JavaFX. I have updated the script to include them, should be working now.

**Comment by TheRareFox** [comment]
I took a look at it ->
![image](https://github.com/user-attachments/assets/367f3ed8-4624-4c45-8324-ec2ab0171ab3)
![image](https://github.com/user-attachments/assets/b400de5f-42aa-4554-845e-a90c3b595187)
![image](https://github.com/user-attachments/assets/e6198eb9-d92b-4d31-a1b6-4e1b7a8410e8)

From what I can tell, every functionality works as intended. I like the unique UI and animation playing in the background, and automatic resizing also works, although can consider locking resizing of height due to the white bar. Maybe consider adding some way a user can quit the system other than outright closing the window with x button, but overall very impressive and good work. 👍

**Comment by somethingfishyfishy** [comment]
Hi there,

Do allow me some time, perhaps over the first few days of recess week. I have just undergone a surgery and I still have my ip that is not done. Understand that the ip is due this Sunday and I may be giving feedback after the deadline but I hope we can take this as a learning process thanks.

**Comment by SuhailLoya** [comment]
Works fine on Mac and I like the moving animation background. One feedback is to show maybe like the previous 5 commands on main screen so the user can still see the output of previous command (example list) while typing new commands.

<img width="787" alt="Screenshot 2024-09-20 at 4 57 18 PM" src="https://github.com/user-attachments/assets/6163a915-bd2e-488c-af15-70cc0cbca198">

**Comment by jayjay19630** [comment]
> Works fine on Mac and I like the moving animation background. One feedback is to show maybe like the previous 5 commands on main screen so the user can still see the output of previous command (example list) while typing new commands.
> 
> <img alt="Screenshot 2024-09-20 at 4 57 18 PM" width="787" src="https://private-user-images.githubusercontent.com/56491340/369337737-6163a915-bd2e-488c-af15-70cc0cbca198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODkwNTEsIm5iZiI6MTcyNjg4ODc1MSwicGF0aCI6Ii81NjQ5MTM0MC8zNjkzMzc3MzctNjE2M2E5MTUtYmQyZS00ODhjLWFmMTUtNzBjYzBjYmNhMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAzMTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjIwZWQ3MjZiNDM2MDE2ZDQ5ZWE3MTk3YTgxMmE0NDQxNmZkZDg3MzgwMDY0NzM2ZTU4MjIzMTMwNTU1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zw284L3q27RRIzvnvEneMWhQb39o4IhtkY7_dpPJtCE">

I did intentionally show only the single last command to mimic more of a game RPG style of interaction between the user and GLaDOS. However, I do agree that it might become a hassle if you want to check list and then mark/unmark. Thanks for the feedback, I will consider this as I work on my next release!
